http:
  port: 8080
admin:
  port: 9876
  host: localhost
log:
  level: debug
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  seismicData:
    host: "localhost"
    paths: "/seismic/*"
  daylightData:
    host: "localhost"
    paths: "/daylight/*"
  isslocationData:
    host: "localhost"
    paths: "/iss-now"
  spaceData:
    host: "localhost"
    paths: "/astros"
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  seismic:
    url: "https://65ca483b3b05d29307e01640.mockapi.io/api"
  daylight:
    url: "https://65ca483b3b05d29307e01640.mockapi.io/api"
  iss:
    url: "http://api.open-notify.org"
    
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  seismic:
    apiEndpoints:
      - seismicData
    policies:
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - proxy:
          - action:
              serviceEndpoint: seismic
              changeOrigin: true

  daylight:
    apiEndpoints:
      - daylightData
    policies:
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - proxy:
          - action:
              serviceEndpoint: daylight
              changeOrigin: true
  isslocation:
    apiEndpoints:
      - isslocationData
    policies:
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - proxy:
          - action:
              serviceEndpoint: iss
              changeOrigin: true
  spacelocation:
    apiEndpoints:
      - spaceData
    policies:
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - proxy:
          - action:
              serviceEndpoint: iss
              changeOrigin: true

 
  

